version: '2.0'
networks:
  intranet:
    ipam:
      config:
        - subnet: 192.168.200.0/24

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S1st3m4s
      MYSQL_DATABASE: Income
      MYSQL_USER: admin
      MYSQL_PASSWORD: S1st3m4s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      intranet:
        ipv4_address: 192.168.200.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: S1st3m4s
    depends_on:
      - db
    networks:
      intranet:
        ipv4_address: 192.168.200.3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: bash -c "chmod -R 777 storage && apache2-foreground && apt-get install nano"
    networks:
      intranet:
        ipv4_address: 192.168.200.5
volumes:
  db_data:
